# Die analyse Bilder erst mit Vertriebler zu diskutieren
import os
import subprocess
from jinja2 import Template

def generate_pdf(data, output_pdf="output.pdf"):
    #Path to the LaTeX template
    template_path = "Template.tex"

    # Read the LaTeX template
    with open(template_path, 'r') as file:
        template_content = file.read()
    
    # Save it as variable 
    template = Template(template_content)
    rendered_content = template.render(data=data)

    # Write the rendered LaTex content to a .tex file
    tex_file = "output.tex"
    with open(tex_file, 'w') as file:
        file.write(rendered_content)

    # Compile the .tex file into a PDF using pdflatex
    try:
        subprocess.run(["pdflatex", "-interaction=nonstopmode", tex_file], check=True)
        print(f"PDF generated successfully: {output_pdf}")
    except subprocess.CalledProcessError as e:
        print("Error during PDF generation:", e)
    finally:
        # Clean up auxiliary files generated by pdflatex
        for ext in [".aux", ".log", ".tex"]:
            if os.path.exists(f"output{ext}"):
                os.remove(f"output{ext}")

# Example usage
if __name__ == "__main__":
    # Dynamic data to insert into the PDF
    data = {
        "name": "John Doe",
        "row1_col1": "Value 1.1",
        "row1_col2": "Value 1.2",
        "row1_col3": "Value 1.3",
        "row2_col1": "Value 2.1",
        "row2_col2": "Value 2.2",
        "row2_col3": "Value 2.3",
        "row3_col1": "Value 3.1",
        "row3_col2": "Value 3.2",
        "row3_col3": "Value 3.3",
    }

    generate_pdf(data) 
